services:
  - type: web
    name: myebook
    runtime: php8.2
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan optimize
      php artisan migrate --force
    startCommand: php artisan serve
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false