services:
  - type: web
    name: my-laravel-app
    plan: free
    dockerfilePath: Dockerfile
    disk:
      name: laravel_storage
      mountPath: /var/www/html/storage
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
